# Adapted from FPComplete's Haskell Travis Config:
#   https://www.fpcomplete.com/blog/2016/02/updated-haskell-travis-config

# Choose a lightweight base image; we provide our own tools.
language: c

# The following two lines seem to improve performance.
dist: trusty
sudo: required

cache:
  # Our caches are large, and take long enough to upload that we sometimes hit
  # the default timeout of 180s, so we extend it here
  timeout: 1500
  directories:
    - $HOME/.stack

branches:
  # Only build master and tagged versions, i.e. not feature branches; feature
  # branches already get built after opening a pull request.
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/


addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH

script:
  - ./travis/timeout.sh ./travis/script.sh

notifications:
  email: true

before_deploy:
  - mkdir bundle
  - cp `stack path --dist-dir`/build/pursuit/pursuit bundle/
  - cp LICENSE bundle/
  - tar czf pursuit.tar.gz -C bundle/ .

deploy:
  provider: releases
  api_key: $RELEASE_KEY
  file: pursuit.tar.gz
  skip_cleanup: true
  on:
    tags: true
